name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install -y libx11-dev libx11-xcb-dev libxcb-xkb-dev libxft-dev libgcr-3-dev libwebkit2gtk-4.0-dev
    - name: Build
      run: make

